### ISSUE TITLE
Obtenção dos artigos

### ISSUE THREAD

**Issue by edipoalex** [edipoalex/noticias_tec_crawler#1]
Prezados,
Gostaria de saber se a captura dos artigos deve ocorrer de forma full ou apenas as do dia?

**Comment by marpontes** [comment]
Pode ser parcial, desde que, de alguma forma, você consiga documentar ou ilustrar o que há ingerido na sua base.

**Comment by edipoalex** [comment]
Ok Marcelo. Perguntei, pois a captura pode ocorrer obtendo apenas os dados da página inicial, onde ficam as notícias do dia, ou pode ser full, onde o crawler vai passando todas as páginas. Mas essa segunda opção acho mais arriscado, pois o crawler pode ser bloqueado pelo site. Então, vou raspar apenas a página inicial, acessar os links das notícias e obter os dados solicitados.

**Comment by marpontes** [comment]
Existem outras abordagens de indexação do conteúdo.

Ex.:
* Sitemaps,
* Rss,
* Engenharia reversa de APIs do proprio site

Não precisa necessariamente de crawler profundo.

**Comment by edipoalex** [comment]
Tranquilo! Já criei o crawler usando o scrapy. Ainda não consegui subir aqui porque estou tendo alguns problemas com o git. Mas vou tentar subir ainda hoje. Estou mais refinando e alinhando a solução com a proposta do desafio com base nas dúvidas que elenquei.
