### ISSUE TITLE
Obtenção dos artigos II

### ISSUE THREAD

**Issue by edipoalex** [edipoalex/noticias_tec_crawler#2]
Quanto a captura, deverá ocorrer apenas através da primeira página, ou deverá seguir o link do artigo para acessar a sua página e obter todo o conteúdo?

**Comment by marpontes** [comment]
O objetivo do desafio é obter dados relevantes sobre o artigo, como autor, datas, corpo, tags. Assim, é necessário ler a _view_ do conteúdo também.
